# .pre-commit-config.yaml
repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0 # Use the latest version
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: .pre-commit-config.yaml # Don't scan the config file itself